import type { ComponentType, SVGProps } from "react";
import {
  Search,
  Check,
  X as Close,
  AlertCircle,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  Pencil,
  Trash2,
  Info,
  Settings,
  Filter,
  Calendar,
  Download,
  Upload,
  Eye,
  EyeOff,
  ArrowLeft,
  ArrowRight,
  AlertTriangle,
  CheckCircle2,
  MinusCircle,
  RefreshCw,
  Loader2,
  Flame,
  Zap,
  Send,
  Sparkles,
  RotateCw,
  FileClock,
  GitCompare,
  Paperclip,
  FileText,
  Clock,
  History,
  ShieldAlert,
  Scale,
  Archive,
  FileX,
  TrendingDown,
  PanelRight,
} from "lucide-react";

/**
 * Имя иконки из @sber-orm/ui-kit (keyof typeof EIconName).
 * До установки пакета используем строковый алиас + локальный реестр (lucide).
 * Контракт: ALL_COMPONENTS.md → EIconName.
 */
export type IconName = string;

const registry: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  search: Search,
  check: Check,
  close: Close,
  errorRounded: AlertCircle,
  info: Info,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  plus: Plus,
  minus: Minus,
  edit: Pencil,
  trash: Trash2,
  settings: Settings,
  filter: Filter,
  calendar: Calendar,
  download: Download,
  upload: Upload,
  eye: Eye,
  eyeOff: EyeOff,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  alertTriangle: AlertTriangle,
  warning: AlertTriangle,
  checkCircle: CheckCircle2,
  minusCircle: MinusCircle,
  refresh: RefreshCw,
  spinner: Loader2,
  loader: Loader2,
  flame: Flame,
  zap: Zap,
  send: Send,
  sparkles: Sparkles,
  rotate: RotateCw,
  fileClock: FileClock,
  gitCompare: GitCompare,
  paperclip: Paperclip,
  file: FileText,
  fileText: FileText,
  clock: Clock,
  history: History,
  shieldAlert: ShieldAlert,
  scale: Scale,
  archive: Archive,
  fileX: FileX,
  trendingDown: TrendingDown,
  panelRight: PanelRight,
};

export function resolveIcon(name: IconName): ComponentType<SVGProps<SVGSVGElement>> | null {
  return registry[name] ?? null;
}